name: "montedesantiago"
services:
  webserver:
    build:
      context: .
      dockerfile: dockerfiles/webserver.dockerfile
    container_name: montedesantiago_webserver
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./dockerfiles/custom-nginx.conf:/etc/nginx/conf.d/custom-nginx.conf
      - ./dockerfiles/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    restart: unless-stopped

  mariadb:
    build:
      context: .
      dockerfile: dockerfiles/mariadb.dockerfile
    container_name: montedesantiago_mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=app_mysql_root_password
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_mysql_app_user_password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'

  phpmyadmin:
    build:
      context: .
      dockerfile: dockerfiles/phpmyadmin.dockerfile
    container_name: montedesantiago_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=app_user
      - PMA_PASSWORD=app_mysql_app_user_password

volumes:
  mariadb_data: